/*
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.ide.contentassist.antlr;

import ca.uottawa.csmlab.symboleo.ide.contentassist.antlr.internal.InternalSymboleoParser;
import ca.uottawa.csmlab.symboleo.services.SymboleoGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class SymboleoParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SymboleoGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SymboleoGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDomainTypeAccess().getAlternatives(), "rule__DomainType__Alternatives");
			builder.put(grammarAccess.getRegularTypeAccess().getAlternatives(), "rule__RegularType__Alternatives");
			builder.put(grammarAccess.getRegularTypeAccess().getAlternatives_0_1(), "rule__RegularType__Alternatives_0_1");
			builder.put(grammarAccess.getRegularTypeAccess().getAlternatives_1_1(), "rule__RegularType__Alternatives_1_1");
			builder.put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
			builder.put(grammarAccess.getBaseTypeAccess().getNameAlternatives_0(), "rule__BaseType__NameAlternatives_0");
			builder.put(grammarAccess.getOntologyTypeAccess().getNameAlternatives_0(), "rule__OntologyType__NameAlternatives_0");
			builder.put(grammarAccess.getParameterTypeAccess().getAlternatives(), "rule__ParameterType__Alternatives");
			builder.put(grammarAccess.getEqualityAccess().getOpAlternatives_1_1_0(), "rule__Equality__OpAlternatives_1_1_0");
			builder.put(grammarAccess.getComparisonAccess().getOpAlternatives_1_1_0(), "rule__Comparison__OpAlternatives_1_1_0");
			builder.put(grammarAccess.getAdditionAccess().getAlternatives_1_0(), "rule__Addition__Alternatives_1_0");
			builder.put(grammarAccess.getMultiplicationAccess().getAlternatives_1_0(), "rule__Multiplication__Alternatives_1_0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
			builder.put(grammarAccess.getAtomicExpressionAccess().getAlternatives(), "rule__AtomicExpression__Alternatives");
			builder.put(grammarAccess.getFunctionCallAccess().getAlternatives(), "rule__FunctionCall__Alternatives");
			builder.put(grammarAccess.getMathFunctionAccess().getAlternatives(), "rule__MathFunction__Alternatives");
			builder.put(grammarAccess.getMathFunctionAccess().getNameAlternatives_1_1_0(), "rule__MathFunction__NameAlternatives_1_1_0");
			builder.put(grammarAccess.getStringFunctionAccess().getAlternatives(), "rule__StringFunction__Alternatives");
			builder.put(grammarAccess.getStringFunctionAccess().getNameAlternatives_0_1_0(), "rule__StringFunction__NameAlternatives_0_1_0");
			builder.put(grammarAccess.getStringFunctionAccess().getNameAlternatives_2_1_0(), "rule__StringFunction__NameAlternatives_2_1_0");
			builder.put(grammarAccess.getObligationAccess().getAlternatives_3(), "rule__Obligation__Alternatives_3");
			builder.put(grammarAccess.getPowerAccess().getAlternatives_3(), "rule__Power__Alternatives_3");
			builder.put(grammarAccess.getPowerFunctionAccess().getAlternatives(), "rule__PowerFunction__Alternatives");
			builder.put(grammarAccess.getPEqualityAccess().getOpAlternatives_1_1_0(), "rule__PEquality__OpAlternatives_1_1_0");
			builder.put(grammarAccess.getPComparisonAccess().getOpAlternatives_1_1_0(), "rule__PComparison__OpAlternatives_1_1_0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getAlternatives(), "rule__PAtomicExpression__Alternatives");
			builder.put(grammarAccess.getPredicateFunctionAccess().getAlternatives(), "rule__PredicateFunction__Alternatives");
			builder.put(grammarAccess.getOtherFunctionAccess().getAlternatives(), "rule__OtherFunction__Alternatives");
			builder.put(grammarAccess.getEventAccess().getAlternatives(), "rule__Event__Alternatives");
			builder.put(grammarAccess.getPowerEventNameAccess().getAlternatives(), "rule__PowerEventName__Alternatives");
			builder.put(grammarAccess.getObligationEventNameAccess().getAlternatives(), "rule__ObligationEventName__Alternatives");
			builder.put(grammarAccess.getContractEventNameAccess().getAlternatives(), "rule__ContractEventName__Alternatives");
			builder.put(grammarAccess.getPointExpressionAccess().getAlternatives(), "rule__PointExpression__Alternatives");
			builder.put(grammarAccess.getPointAtomAccess().getAlternatives(), "rule__PointAtom__Alternatives");
			builder.put(grammarAccess.getTimevalueAccess().getAlternatives(), "rule__Timevalue__Alternatives");
			builder.put(grammarAccess.getTimeUnitAccess().getAlternatives(), "rule__TimeUnit__Alternatives");
			builder.put(grammarAccess.getIntervalExpressionAccess().getAlternatives(), "rule__IntervalExpression__Alternatives");
			builder.put(grammarAccess.getSituationAccess().getAlternatives(), "rule__Situation__Alternatives");
			builder.put(grammarAccess.getPowerStateNameAccess().getAlternatives(), "rule__PowerStateName__Alternatives");
			builder.put(grammarAccess.getObligationStateNameAccess().getAlternatives(), "rule__ObligationStateName__Alternatives");
			builder.put(grammarAccess.getContractStateNameAccess().getAlternatives(), "rule__ContractStateName__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_2(), "rule__Model__Group_2__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4(), "rule__Model__Group_4__0");
			builder.put(grammarAccess.getModelAccess().getGroup_8(), "rule__Model__Group_8__0");
			builder.put(grammarAccess.getModelAccess().getGroup_11(), "rule__Model__Group_11__0");
			builder.put(grammarAccess.getModelAccess().getGroup_11_1(), "rule__Model__Group_11_1__0");
			builder.put(grammarAccess.getModelAccess().getGroup_12(), "rule__Model__Group_12__0");
			builder.put(grammarAccess.getModelAccess().getGroup_12_1(), "rule__Model__Group_12_1__0");
			builder.put(grammarAccess.getModelAccess().getGroup_13(), "rule__Model__Group_13__0");
			builder.put(grammarAccess.getModelAccess().getGroup_13_1(), "rule__Model__Group_13_1__0");
			builder.put(grammarAccess.getModelAccess().getGroup_14(), "rule__Model__Group_14__0");
			builder.put(grammarAccess.getModelAccess().getGroup_14_1(), "rule__Model__Group_14_1__0");
			builder.put(grammarAccess.getModelAccess().getGroup_15(), "rule__Model__Group_15__0");
			builder.put(grammarAccess.getModelAccess().getGroup_15_2(), "rule__Model__Group_15_2__0");
			builder.put(grammarAccess.getModelAccess().getGroup_16(), "rule__Model__Group_16__0");
			builder.put(grammarAccess.getModelAccess().getGroup_16_1(), "rule__Model__Group_16_1__0");
			builder.put(grammarAccess.getModelAccess().getGroup_17(), "rule__Model__Group_17__0");
			builder.put(grammarAccess.getModelAccess().getGroup_17_1(), "rule__Model__Group_17_1__0");
			builder.put(grammarAccess.getAliasAccess().getGroup(), "rule__Alias__Group__0");
			builder.put(grammarAccess.getEnumerationAccess().getGroup(), "rule__Enumeration__Group__0");
			builder.put(grammarAccess.getEnumerationAccess().getGroup_4(), "rule__Enumeration__Group_4__0");
			builder.put(grammarAccess.getRegularTypeAccess().getGroup_0(), "rule__RegularType__Group_0__0");
			builder.put(grammarAccess.getRegularTypeAccess().getGroup_0_3(), "rule__RegularType__Group_0_3__0");
			builder.put(grammarAccess.getRegularTypeAccess().getGroup_0_3_1(), "rule__RegularType__Group_0_3_1__0");
			builder.put(grammarAccess.getRegularTypeAccess().getGroup_1(), "rule__RegularType__Group_1__0");
			builder.put(grammarAccess.getRegularTypeAccess().getGroup_1_3(), "rule__RegularType__Group_1_3__0");
			builder.put(grammarAccess.getRegularTypeAccess().getGroup_1_3_1(), "rule__RegularType__Group_1_3_1__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_0(), "rule__Attribute__Group_0__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_1(), "rule__Attribute__Group_1__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_3(), "rule__Variable__Group_3__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_3_2(), "rule__Variable__Group_3_2__0");
			builder.put(grammarAccess.getOAssignmentAccess().getGroup(), "rule__OAssignment__Group__0");
			builder.put(grammarAccess.getVariableDotExpressionAccess().getGroup(), "rule__VariableDotExpression__Group__0");
			builder.put(grammarAccess.getVariableDotExpressionAccess().getGroup_1(), "rule__VariableDotExpression__Group_1__0");
			builder.put(grammarAccess.getVariableRefAccess().getGroup(), "rule__VariableRef__Group__0");
			builder.put(grammarAccess.getAssignmentAccess().getGroup(), "rule__Assignment__Group__0");
			builder.put(grammarAccess.getDoubleAccess().getGroup(), "rule__Double__Group__0");
			builder.put(grammarAccess.getDateAccess().getGroup(), "rule__Date__Group__0");
			builder.put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
			builder.put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
			builder.put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
			builder.put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup(), "rule__Equality__Group__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup_1(), "rule__Equality__Group_1__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup(), "rule__Comparison__Group__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup_1(), "rule__Comparison__Group_1__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup(), "rule__Addition__Group__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup_1(), "rule__Addition__Group_1__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup_1_0_0(), "rule__Addition__Group_1_0_0__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup_1_0_1(), "rule__Addition__Group_1_0_1__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup(), "rule__Multiplication__Group__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup_1(), "rule__Multiplication__Group_1__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup_1_0_0(), "rule__Multiplication__Group_1_0_0__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup_1_0_1(), "rule__Multiplication__Group_1_0_1__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_0(), "rule__PrimaryExpression__Group_0__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_1(), "rule__PrimaryExpression__Group_1__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_2(), "rule__PrimaryExpression__Group_2__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_0(), "rule__AtomicExpression__Group_0__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_1(), "rule__AtomicExpression__Group_1__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_2(), "rule__AtomicExpression__Group_2__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_3(), "rule__AtomicExpression__Group_3__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_4(), "rule__AtomicExpression__Group_4__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_5(), "rule__AtomicExpression__Group_5__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_6(), "rule__AtomicExpression__Group_6__0");
			builder.put(grammarAccess.getAtomicExpressionAccess().getGroup_7(), "rule__AtomicExpression__Group_7__0");
			builder.put(grammarAccess.getMathFunctionAccess().getGroup_0(), "rule__MathFunction__Group_0__0");
			builder.put(grammarAccess.getMathFunctionAccess().getGroup_1(), "rule__MathFunction__Group_1__0");
			builder.put(grammarAccess.getStringFunctionAccess().getGroup_0(), "rule__StringFunction__Group_0__0");
			builder.put(grammarAccess.getStringFunctionAccess().getGroup_1(), "rule__StringFunction__Group_1__0");
			builder.put(grammarAccess.getStringFunctionAccess().getGroup_2(), "rule__StringFunction__Group_2__0");
			builder.put(grammarAccess.getDateFunctionAccess().getGroup(), "rule__DateFunction__Group__0");
			builder.put(grammarAccess.getObligationAccess().getGroup(), "rule__Obligation__Group__0");
			builder.put(grammarAccess.getObligationAccess().getGroup_2(), "rule__Obligation__Group_2__0");
			builder.put(grammarAccess.getPowerAccess().getGroup(), "rule__Power__Group__0");
			builder.put(grammarAccess.getPowerAccess().getGroup_2(), "rule__Power__Group_2__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_0(), "rule__PowerFunction__Group_0__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_1(), "rule__PowerFunction__Group_1__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_2(), "rule__PowerFunction__Group_2__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_3(), "rule__PowerFunction__Group_3__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_4(), "rule__PowerFunction__Group_4__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_5(), "rule__PowerFunction__Group_5__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_6(), "rule__PowerFunction__Group_6__0");
			builder.put(grammarAccess.getPowerFunctionAccess().getGroup_7(), "rule__PowerFunction__Group_7__0");
			builder.put(grammarAccess.getPOrAccess().getGroup(), "rule__POr__Group__0");
			builder.put(grammarAccess.getPOrAccess().getGroup_1(), "rule__POr__Group_1__0");
			builder.put(grammarAccess.getPAndAccess().getGroup(), "rule__PAnd__Group__0");
			builder.put(grammarAccess.getPAndAccess().getGroup_1(), "rule__PAnd__Group_1__0");
			builder.put(grammarAccess.getPEqualityAccess().getGroup(), "rule__PEquality__Group__0");
			builder.put(grammarAccess.getPEqualityAccess().getGroup_1(), "rule__PEquality__Group_1__0");
			builder.put(grammarAccess.getPComparisonAccess().getGroup(), "rule__PComparison__Group__0");
			builder.put(grammarAccess.getPComparisonAccess().getGroup_1(), "rule__PComparison__Group_1__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_0(), "rule__PAtomicExpression__Group_0__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_1(), "rule__PAtomicExpression__Group_1__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_2(), "rule__PAtomicExpression__Group_2__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_3(), "rule__PAtomicExpression__Group_3__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_4(), "rule__PAtomicExpression__Group_4__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_5(), "rule__PAtomicExpression__Group_5__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_6(), "rule__PAtomicExpression__Group_6__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_7(), "rule__PAtomicExpression__Group_7__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_8(), "rule__PAtomicExpression__Group_8__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_9(), "rule__PAtomicExpression__Group_9__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_10(), "rule__PAtomicExpression__Group_10__0");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getGroup_11(), "rule__PAtomicExpression__Group_11__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_0(), "rule__PredicateFunction__Group_0__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_1(), "rule__PredicateFunction__Group_1__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_2(), "rule__PredicateFunction__Group_2__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_3(), "rule__PredicateFunction__Group_3__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_4(), "rule__PredicateFunction__Group_4__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_5(), "rule__PredicateFunction__Group_5__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_6(), "rule__PredicateFunction__Group_6__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_7(), "rule__PredicateFunction__Group_7__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_8(), "rule__PredicateFunction__Group_8__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_8_5(), "rule__PredicateFunction__Group_8_5__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_8_5_1(), "rule__PredicateFunction__Group_8_5_1__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_9(), "rule__PredicateFunction__Group_9__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_9_3(), "rule__PredicateFunction__Group_9_3__0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getGroup_9_3_1(), "rule__PredicateFunction__Group_9_3_1__0");
			builder.put(grammarAccess.getOtherFunctionAccess().getGroup_0(), "rule__OtherFunction__Group_0__0");
			builder.put(grammarAccess.getOtherFunctionAccess().getGroup_1(), "rule__OtherFunction__Group_1__0");
			builder.put(grammarAccess.getOtherFunctionAccess().getGroup_2(), "rule__OtherFunction__Group_2__0");
			builder.put(grammarAccess.getVariableEventAccess().getGroup(), "rule__VariableEvent__Group__0");
			builder.put(grammarAccess.getPowerEventAccess().getGroup(), "rule__PowerEvent__Group__0");
			builder.put(grammarAccess.getObligationEventAccess().getGroup(), "rule__ObligationEvent__Group__0");
			builder.put(grammarAccess.getContractEventAccess().getGroup(), "rule__ContractEvent__Group__0");
			builder.put(grammarAccess.getPointFunctionAccess().getGroup(), "rule__PointFunction__Group__0");
			builder.put(grammarAccess.getPointAtomAccess().getGroup_0(), "rule__PointAtom__Group_0__0");
			builder.put(grammarAccess.getPointAtomAccess().getGroup_1(), "rule__PointAtom__Group_1__0");
			builder.put(grammarAccess.getPointAtomAccess().getGroup_2(), "rule__PointAtom__Group_2__0");
			builder.put(grammarAccess.getPointAtomAccess().getGroup_3(), "rule__PointAtom__Group_3__0");
			builder.put(grammarAccess.getTimevalueAccess().getGroup_0(), "rule__Timevalue__Group_0__0");
			builder.put(grammarAccess.getTimevalueAccess().getGroup_1(), "rule__Timevalue__Group_1__0");
			builder.put(grammarAccess.getIntervalExpressionAccess().getGroup_0(), "rule__IntervalExpression__Group_0__0");
			builder.put(grammarAccess.getIntervalExpressionAccess().getGroup_1(), "rule__IntervalExpression__Group_1__0");
			builder.put(grammarAccess.getPowerStateAccess().getGroup(), "rule__PowerState__Group__0");
			builder.put(grammarAccess.getObligationStateAccess().getGroup(), "rule__ObligationState__Group__0");
			builder.put(grammarAccess.getContractStateAccess().getGroup(), "rule__ContractState__Group__0");
			builder.put(grammarAccess.getModelAccess().getDomainNameAssignment_1(), "rule__Model__DomainNameAssignment_1");
			builder.put(grammarAccess.getModelAccess().getDomainTypesAssignment_2_0(), "rule__Model__DomainTypesAssignment_2_0");
			builder.put(grammarAccess.getModelAccess().getTimeUnitsAssignment_4_2(), "rule__Model__TimeUnitsAssignment_4_2");
			builder.put(grammarAccess.getModelAccess().getContractNameAssignment_6(), "rule__Model__ContractNameAssignment_6");
			builder.put(grammarAccess.getModelAccess().getParametersAssignment_8_0(), "rule__Model__ParametersAssignment_8_0");
			builder.put(grammarAccess.getModelAccess().getParametersAssignment_9(), "rule__Model__ParametersAssignment_9");
			builder.put(grammarAccess.getModelAccess().getVariablesAssignment_11_1_0(), "rule__Model__VariablesAssignment_11_1_0");
			builder.put(grammarAccess.getModelAccess().getPreconditionsAssignment_12_1_0(), "rule__Model__PreconditionsAssignment_12_1_0");
			builder.put(grammarAccess.getModelAccess().getPostconditionsAssignment_13_1_0(), "rule__Model__PostconditionsAssignment_13_1_0");
			builder.put(grammarAccess.getModelAccess().getObligationsAssignment_14_1_0(), "rule__Model__ObligationsAssignment_14_1_0");
			builder.put(grammarAccess.getModelAccess().getSurvivingObligationsAssignment_15_2_0(), "rule__Model__SurvivingObligationsAssignment_15_2_0");
			builder.put(grammarAccess.getModelAccess().getPowersAssignment_16_1_0(), "rule__Model__PowersAssignment_16_1_0");
			builder.put(grammarAccess.getModelAccess().getConstraintsAssignment_17_1_0(), "rule__Model__ConstraintsAssignment_17_1_0");
			builder.put(grammarAccess.getAliasAccess().getNameAssignment_0(), "rule__Alias__NameAssignment_0");
			builder.put(grammarAccess.getAliasAccess().getTypeAssignment_2(), "rule__Alias__TypeAssignment_2");
			builder.put(grammarAccess.getEnumerationAccess().getNameAssignment_0(), "rule__Enumeration__NameAssignment_0");
			builder.put(grammarAccess.getEnumerationAccess().getEnumerationItemsAssignment_4_0(), "rule__Enumeration__EnumerationItemsAssignment_4_0");
			builder.put(grammarAccess.getEnumerationAccess().getEnumerationItemsAssignment_5(), "rule__Enumeration__EnumerationItemsAssignment_5");
			builder.put(grammarAccess.getEnumItemAccess().getNameAssignment(), "rule__EnumItem__NameAssignment");
			builder.put(grammarAccess.getRegularTypeAccess().getNameAssignment_0_0(), "rule__RegularType__NameAssignment_0_0");
			builder.put(grammarAccess.getRegularTypeAccess().getOntologyTypeAssignment_0_2(), "rule__RegularType__OntologyTypeAssignment_0_2");
			builder.put(grammarAccess.getRegularTypeAccess().getAttributesAssignment_0_3_1_0(), "rule__RegularType__AttributesAssignment_0_3_1_0");
			builder.put(grammarAccess.getRegularTypeAccess().getAttributesAssignment_0_3_2(), "rule__RegularType__AttributesAssignment_0_3_2");
			builder.put(grammarAccess.getRegularTypeAccess().getNameAssignment_1_0(), "rule__RegularType__NameAssignment_1_0");
			builder.put(grammarAccess.getRegularTypeAccess().getRegularTypeAssignment_1_2(), "rule__RegularType__RegularTypeAssignment_1_2");
			builder.put(grammarAccess.getRegularTypeAccess().getAttributesAssignment_1_3_1_0(), "rule__RegularType__AttributesAssignment_1_3_1_0");
			builder.put(grammarAccess.getRegularTypeAccess().getAttributesAssignment_1_3_2(), "rule__RegularType__AttributesAssignment_1_3_2");
			builder.put(grammarAccess.getAttributeAccess().getAttributeModifierAssignment_0_0(), "rule__Attribute__AttributeModifierAssignment_0_0");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_0_1(), "rule__Attribute__NameAssignment_0_1");
			builder.put(grammarAccess.getAttributeAccess().getBaseTypeAssignment_0_3(), "rule__Attribute__BaseTypeAssignment_0_3");
			builder.put(grammarAccess.getAttributeAccess().getAttributeModifierAssignment_1_0(), "rule__Attribute__AttributeModifierAssignment_1_0");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_1_1(), "rule__Attribute__NameAssignment_1_1");
			builder.put(grammarAccess.getAttributeAccess().getDomainTypeAssignment_1_3(), "rule__Attribute__DomainTypeAssignment_1_3");
			builder.put(grammarAccess.getBaseTypeAccess().getNameAssignment(), "rule__BaseType__NameAssignment");
			builder.put(grammarAccess.getOntologyTypeAccess().getNameAssignment(), "rule__OntologyType__NameAssignment");
			builder.put(grammarAccess.getAttributeModifierAccess().getNameAssignment(), "rule__AttributeModifier__NameAssignment");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_0(), "rule__Parameter__NameAssignment_0");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_2(), "rule__Parameter__TypeAssignment_2");
			builder.put(grammarAccess.getParameterTypeAccess().getBaseTypeAssignment_0(), "rule__ParameterType__BaseTypeAssignment_0");
			builder.put(grammarAccess.getParameterTypeAccess().getDomainTypeAssignment_1(), "rule__ParameterType__DomainTypeAssignment_1");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_0(), "rule__Variable__NameAssignment_0");
			builder.put(grammarAccess.getVariableAccess().getTypeAssignment_2(), "rule__Variable__TypeAssignment_2");
			builder.put(grammarAccess.getVariableAccess().getAttributesAssignment_3_1(), "rule__Variable__AttributesAssignment_3_1");
			builder.put(grammarAccess.getVariableAccess().getAttributesAssignment_3_2_1(), "rule__Variable__AttributesAssignment_3_2_1");
			builder.put(grammarAccess.getOAssignmentAccess().getName2Assignment_1(), "rule__OAssignment__Name2Assignment_1");
			builder.put(grammarAccess.getOAssignmentAccess().getOpAssignment_2(), "rule__OAssignment__OpAssignment_2");
			builder.put(grammarAccess.getOAssignmentAccess().getValueAssignment_3(), "rule__OAssignment__ValueAssignment_3");
			builder.put(grammarAccess.getVariableDotExpressionAccess().getTailAssignment_1_2(), "rule__VariableDotExpression__TailAssignment_1_2");
			builder.put(grammarAccess.getVariableRefAccess().getVariableAssignment_1(), "rule__VariableRef__VariableAssignment_1");
			builder.put(grammarAccess.getAssignmentAccess().getNameAssignment_1(), "rule__Assignment__NameAssignment_1");
			builder.put(grammarAccess.getAssignmentAccess().getValueAssignment_3(), "rule__Assignment__ValueAssignment_3");
			builder.put(grammarAccess.getOrAccess().getRightAssignment_1_2(), "rule__Or__RightAssignment_1_2");
			builder.put(grammarAccess.getAndAccess().getRightAssignment_1_2(), "rule__And__RightAssignment_1_2");
			builder.put(grammarAccess.getEqualityAccess().getOpAssignment_1_1(), "rule__Equality__OpAssignment_1_1");
			builder.put(grammarAccess.getEqualityAccess().getRightAssignment_1_2(), "rule__Equality__RightAssignment_1_2");
			builder.put(grammarAccess.getComparisonAccess().getOpAssignment_1_1(), "rule__Comparison__OpAssignment_1_1");
			builder.put(grammarAccess.getComparisonAccess().getRightAssignment_1_2(), "rule__Comparison__RightAssignment_1_2");
			builder.put(grammarAccess.getAdditionAccess().getRightAssignment_1_1(), "rule__Addition__RightAssignment_1_1");
			builder.put(grammarAccess.getMultiplicationAccess().getRightAssignment_1_1(), "rule__Multiplication__RightAssignment_1_1");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getInnerAssignment_0_2(), "rule__PrimaryExpression__InnerAssignment_0_2");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getFunctionAssignment_1_1(), "rule__PrimaryExpression__FunctionAssignment_1_1");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getExpressionAssignment_2_2(), "rule__PrimaryExpression__ExpressionAssignment_2_2");
			builder.put(grammarAccess.getAtomicExpressionAccess().getValueAssignment_0_1(), "rule__AtomicExpression__ValueAssignment_0_1");
			builder.put(grammarAccess.getAtomicExpressionAccess().getValueAssignment_1_1(), "rule__AtomicExpression__ValueAssignment_1_1");
			builder.put(grammarAccess.getAtomicExpressionAccess().getValueAssignment_2_1(), "rule__AtomicExpression__ValueAssignment_2_1");
			builder.put(grammarAccess.getAtomicExpressionAccess().getValueAssignment_3_1(), "rule__AtomicExpression__ValueAssignment_3_1");
			builder.put(grammarAccess.getAtomicExpressionAccess().getValueAssignment_4_1(), "rule__AtomicExpression__ValueAssignment_4_1");
			builder.put(grammarAccess.getAtomicExpressionAccess().getEnumerationAssignment_5_1(), "rule__AtomicExpression__EnumerationAssignment_5_1");
			builder.put(grammarAccess.getAtomicExpressionAccess().getEnumItemAssignment_5_3(), "rule__AtomicExpression__EnumItemAssignment_5_3");
			builder.put(grammarAccess.getAtomicExpressionAccess().getValueAssignment_6_1(), "rule__AtomicExpression__ValueAssignment_6_1");
			builder.put(grammarAccess.getAtomicExpressionAccess().getValueAssignment_7_1(), "rule__AtomicExpression__ValueAssignment_7_1");
			builder.put(grammarAccess.getMathFunctionAccess().getNameAssignment_0_1(), "rule__MathFunction__NameAssignment_0_1");
			builder.put(grammarAccess.getMathFunctionAccess().getArg1Assignment_0_3(), "rule__MathFunction__Arg1Assignment_0_3");
			builder.put(grammarAccess.getMathFunctionAccess().getArg2Assignment_0_5(), "rule__MathFunction__Arg2Assignment_0_5");
			builder.put(grammarAccess.getMathFunctionAccess().getNameAssignment_1_1(), "rule__MathFunction__NameAssignment_1_1");
			builder.put(grammarAccess.getMathFunctionAccess().getArg1Assignment_1_3(), "rule__MathFunction__Arg1Assignment_1_3");
			builder.put(grammarAccess.getStringFunctionAccess().getNameAssignment_0_1(), "rule__StringFunction__NameAssignment_0_1");
			builder.put(grammarAccess.getStringFunctionAccess().getArg1Assignment_0_3(), "rule__StringFunction__Arg1Assignment_0_3");
			builder.put(grammarAccess.getStringFunctionAccess().getArg2Assignment_0_5(), "rule__StringFunction__Arg2Assignment_0_5");
			builder.put(grammarAccess.getStringFunctionAccess().getArg3Assignment_0_7(), "rule__StringFunction__Arg3Assignment_0_7");
			builder.put(grammarAccess.getStringFunctionAccess().getNameAssignment_1_1(), "rule__StringFunction__NameAssignment_1_1");
			builder.put(grammarAccess.getStringFunctionAccess().getArg1Assignment_1_3(), "rule__StringFunction__Arg1Assignment_1_3");
			builder.put(grammarAccess.getStringFunctionAccess().getArg2Assignment_1_5(), "rule__StringFunction__Arg2Assignment_1_5");
			builder.put(grammarAccess.getStringFunctionAccess().getNameAssignment_2_1(), "rule__StringFunction__NameAssignment_2_1");
			builder.put(grammarAccess.getStringFunctionAccess().getArg1Assignment_2_3(), "rule__StringFunction__Arg1Assignment_2_3");
			builder.put(grammarAccess.getDateFunctionAccess().getNameAssignment_1(), "rule__DateFunction__NameAssignment_1");
			builder.put(grammarAccess.getDateFunctionAccess().getArg1Assignment_3(), "rule__DateFunction__Arg1Assignment_3");
			builder.put(grammarAccess.getDateFunctionAccess().getValueAssignment_5(), "rule__DateFunction__ValueAssignment_5");
			builder.put(grammarAccess.getDateFunctionAccess().getTimeUnitAssignment_7(), "rule__DateFunction__TimeUnitAssignment_7");
			builder.put(grammarAccess.getObligationAccess().getNameAssignment_0(), "rule__Obligation__NameAssignment_0");
			builder.put(grammarAccess.getObligationAccess().getTriggerAssignment_2_0(), "rule__Obligation__TriggerAssignment_2_0");
			builder.put(grammarAccess.getObligationAccess().getDebtorAssignment_5(), "rule__Obligation__DebtorAssignment_5");
			builder.put(grammarAccess.getObligationAccess().getCreditorAssignment_7(), "rule__Obligation__CreditorAssignment_7");
			builder.put(grammarAccess.getObligationAccess().getAntecedentAssignment_9(), "rule__Obligation__AntecedentAssignment_9");
			builder.put(grammarAccess.getObligationAccess().getConsequentAssignment_11(), "rule__Obligation__ConsequentAssignment_11");
			builder.put(grammarAccess.getPowerAccess().getNameAssignment_0(), "rule__Power__NameAssignment_0");
			builder.put(grammarAccess.getPowerAccess().getTriggerAssignment_2_0(), "rule__Power__TriggerAssignment_2_0");
			builder.put(grammarAccess.getPowerAccess().getCreditorAssignment_5(), "rule__Power__CreditorAssignment_5");
			builder.put(grammarAccess.getPowerAccess().getDebtorAssignment_7(), "rule__Power__DebtorAssignment_7");
			builder.put(grammarAccess.getPowerAccess().getAntecedentAssignment_9(), "rule__Power__AntecedentAssignment_9");
			builder.put(grammarAccess.getPowerAccess().getConsequentAssignment_11(), "rule__Power__ConsequentAssignment_11");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_0_1(), "rule__PowerFunction__ActionAssignment_0_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_0_4(), "rule__PowerFunction__NormAssignment_0_4");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_1_1(), "rule__PowerFunction__ActionAssignment_1_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_1_4(), "rule__PowerFunction__NormAssignment_1_4");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_2_1(), "rule__PowerFunction__ActionAssignment_2_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_2_4(), "rule__PowerFunction__NormAssignment_2_4");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_3_1(), "rule__PowerFunction__ActionAssignment_3_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_3_4(), "rule__PowerFunction__NormAssignment_3_4");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_4_1(), "rule__PowerFunction__ActionAssignment_4_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_4_4(), "rule__PowerFunction__NormAssignment_4_4");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_5_1(), "rule__PowerFunction__ActionAssignment_5_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_5_3(), "rule__PowerFunction__NormAssignment_5_3");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_6_1(), "rule__PowerFunction__ActionAssignment_6_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_6_3(), "rule__PowerFunction__NormAssignment_6_3");
			builder.put(grammarAccess.getPowerFunctionAccess().getActionAssignment_7_1(), "rule__PowerFunction__ActionAssignment_7_1");
			builder.put(grammarAccess.getPowerFunctionAccess().getNormAssignment_7_3(), "rule__PowerFunction__NormAssignment_7_3");
			builder.put(grammarAccess.getPOrAccess().getRightAssignment_1_2(), "rule__POr__RightAssignment_1_2");
			builder.put(grammarAccess.getPAndAccess().getRightAssignment_1_2(), "rule__PAnd__RightAssignment_1_2");
			builder.put(grammarAccess.getPEqualityAccess().getOpAssignment_1_1(), "rule__PEquality__OpAssignment_1_1");
			builder.put(grammarAccess.getPEqualityAccess().getRightAssignment_1_2(), "rule__PEquality__RightAssignment_1_2");
			builder.put(grammarAccess.getPComparisonAccess().getOpAssignment_1_1(), "rule__PComparison__OpAssignment_1_1");
			builder.put(grammarAccess.getPComparisonAccess().getRightAssignment_1_2(), "rule__PComparison__RightAssignment_1_2");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getInnerAssignment_0_2(), "rule__PAtomicExpression__InnerAssignment_0_2");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getNegatedAssignment_1_2(), "rule__PAtomicExpression__NegatedAssignment_1_2");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getPredicateFunctionAssignment_2_1(), "rule__PAtomicExpression__PredicateFunctionAssignment_2_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getFunctionAssignment_3_1(), "rule__PAtomicExpression__FunctionAssignment_3_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getEnumerationAssignment_4_1(), "rule__PAtomicExpression__EnumerationAssignment_4_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getEnumItemAssignment_4_3(), "rule__PAtomicExpression__EnumItemAssignment_4_3");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getVariableAssignment_5_1(), "rule__PAtomicExpression__VariableAssignment_5_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getValueAssignment_6_1(), "rule__PAtomicExpression__ValueAssignment_6_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getValueAssignment_7_1(), "rule__PAtomicExpression__ValueAssignment_7_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getValueAssignment_8_1(), "rule__PAtomicExpression__ValueAssignment_8_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getValueAssignment_9_1(), "rule__PAtomicExpression__ValueAssignment_9_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getValueAssignment_10_1(), "rule__PAtomicExpression__ValueAssignment_10_1");
			builder.put(grammarAccess.getPAtomicExpressionAccess().getValueAssignment_11_1(), "rule__PAtomicExpression__ValueAssignment_11_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_0_1(), "rule__PredicateFunction__NameAssignment_0_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEventAssignment_0_3(), "rule__PredicateFunction__EventAssignment_0_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_1_1(), "rule__PredicateFunction__NameAssignment_1_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEventAssignment_1_3(), "rule__PredicateFunction__EventAssignment_1_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getPointAssignment_1_5(), "rule__PredicateFunction__PointAssignment_1_5");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_2_1(), "rule__PredicateFunction__NameAssignment_2_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEventAssignment_2_3(), "rule__PredicateFunction__EventAssignment_2_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getPointAssignment_2_5(), "rule__PredicateFunction__PointAssignment_2_5");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_3_1(), "rule__PredicateFunction__NameAssignment_3_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEventAssignment_3_3(), "rule__PredicateFunction__EventAssignment_3_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getIntervalAssignment_3_5(), "rule__PredicateFunction__IntervalAssignment_3_5");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_4_1(), "rule__PredicateFunction__NameAssignment_4_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEvent1Assignment_4_3(), "rule__PredicateFunction__Event1Assignment_4_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEvent2Assignment_4_5(), "rule__PredicateFunction__Event2Assignment_4_5");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_5_1(), "rule__PredicateFunction__NameAssignment_5_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEvent1Assignment_5_3(), "rule__PredicateFunction__Event1Assignment_5_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEvent2Assignment_5_5(), "rule__PredicateFunction__Event2Assignment_5_5");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_6_1(), "rule__PredicateFunction__NameAssignment_6_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEventAssignment_6_3(), "rule__PredicateFunction__EventAssignment_6_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getPointAssignment_6_5(), "rule__PredicateFunction__PointAssignment_6_5");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_7_1(), "rule__PredicateFunction__NameAssignment_7_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getSituationAssignment_7_3(), "rule__PredicateFunction__SituationAssignment_7_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getIntervalAssignment_7_5(), "rule__PredicateFunction__IntervalAssignment_7_5");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_8_1(), "rule__PredicateFunction__NameAssignment_8_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getEventAssignment_8_3(), "rule__PredicateFunction__EventAssignment_8_3");
			builder.put(grammarAccess.getPredicateFunctionAccess().getAssignmentAssignment_8_5_0(), "rule__PredicateFunction__AssignmentAssignment_8_5_0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getAssignmentAssignment_8_5_1_1(), "rule__PredicateFunction__AssignmentAssignment_8_5_1_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getNameAssignment_9_1(), "rule__PredicateFunction__NameAssignment_9_1");
			builder.put(grammarAccess.getPredicateFunctionAccess().getAssignmentAssignment_9_3_0(), "rule__PredicateFunction__AssignmentAssignment_9_3_0");
			builder.put(grammarAccess.getPredicateFunctionAccess().getAssignmentAssignment_9_3_1_1(), "rule__PredicateFunction__AssignmentAssignment_9_3_1_1");
			builder.put(grammarAccess.getOtherFunctionAccess().getNameAssignment_0_1(), "rule__OtherFunction__NameAssignment_0_1");
			builder.put(grammarAccess.getOtherFunctionAccess().getArg1Assignment_0_3(), "rule__OtherFunction__Arg1Assignment_0_3");
			builder.put(grammarAccess.getOtherFunctionAccess().getArg2Assignment_0_5(), "rule__OtherFunction__Arg2Assignment_0_5");
			builder.put(grammarAccess.getOtherFunctionAccess().getNameAssignment_1_1(), "rule__OtherFunction__NameAssignment_1_1");
			builder.put(grammarAccess.getOtherFunctionAccess().getArg1Assignment_1_3(), "rule__OtherFunction__Arg1Assignment_1_3");
			builder.put(grammarAccess.getOtherFunctionAccess().getArg2Assignment_1_5(), "rule__OtherFunction__Arg2Assignment_1_5");
			builder.put(grammarAccess.getOtherFunctionAccess().getNameAssignment_2_1(), "rule__OtherFunction__NameAssignment_2_1");
			builder.put(grammarAccess.getOtherFunctionAccess().getArg1Assignment_2_3(), "rule__OtherFunction__Arg1Assignment_2_3");
			builder.put(grammarAccess.getVariableEventAccess().getVariableAssignment_1(), "rule__VariableEvent__VariableAssignment_1");
			builder.put(grammarAccess.getPowerEventAccess().getEventNameAssignment_1(), "rule__PowerEvent__EventNameAssignment_1");
			builder.put(grammarAccess.getPowerEventAccess().getPowerVariableAssignment_4(), "rule__PowerEvent__PowerVariableAssignment_4");
			builder.put(grammarAccess.getObligationEventAccess().getEventNameAssignment_1(), "rule__ObligationEvent__EventNameAssignment_1");
			builder.put(grammarAccess.getObligationEventAccess().getObligationVariableAssignment_4(), "rule__ObligationEvent__ObligationVariableAssignment_4");
			builder.put(grammarAccess.getContractEventAccess().getEventNameAssignment_1(), "rule__ContractEvent__EventNameAssignment_1");
			builder.put(grammarAccess.getPointAccess().getPointExpressionAssignment(), "rule__Point__PointExpressionAssignment");
			builder.put(grammarAccess.getPointFunctionAccess().getNameAssignment_1(), "rule__PointFunction__NameAssignment_1");
			builder.put(grammarAccess.getPointFunctionAccess().getArgAssignment_3(), "rule__PointFunction__ArgAssignment_3");
			builder.put(grammarAccess.getPointFunctionAccess().getValueAssignment_5(), "rule__PointFunction__ValueAssignment_5");
			builder.put(grammarAccess.getPointFunctionAccess().getTimeUnitAssignment_7(), "rule__PointFunction__TimeUnitAssignment_7");
			builder.put(grammarAccess.getPointAtomAccess().getVariableAssignment_0_1(), "rule__PointAtom__VariableAssignment_0_1");
			builder.put(grammarAccess.getPointAtomAccess().getObligationEventAssignment_1_1(), "rule__PointAtom__ObligationEventAssignment_1_1");
			builder.put(grammarAccess.getPointAtomAccess().getContractEventAssignment_2_1(), "rule__PointAtom__ContractEventAssignment_2_1");
			builder.put(grammarAccess.getPointAtomAccess().getPowerEventAssignment_3_1(), "rule__PointAtom__PowerEventAssignment_3_1");
			builder.put(grammarAccess.getTimevalueAccess().getValueAssignment_0_1(), "rule__Timevalue__ValueAssignment_0_1");
			builder.put(grammarAccess.getTimevalueAccess().getVariableAssignment_1_1(), "rule__Timevalue__VariableAssignment_1_1");
			builder.put(grammarAccess.getIntervalAccess().getIntervalExpressionAssignment(), "rule__Interval__IntervalExpressionAssignment");
			builder.put(grammarAccess.getIntervalExpressionAccess().getArg1Assignment_0_3(), "rule__IntervalExpression__Arg1Assignment_0_3");
			builder.put(grammarAccess.getIntervalExpressionAccess().getArg2Assignment_0_5(), "rule__IntervalExpression__Arg2Assignment_0_5");
			builder.put(grammarAccess.getIntervalExpressionAccess().getSituationAssignment_1_1(), "rule__IntervalExpression__SituationAssignment_1_1");
			builder.put(grammarAccess.getPowerStateAccess().getStateNameAssignment_0(), "rule__PowerState__StateNameAssignment_0");
			builder.put(grammarAccess.getPowerStateAccess().getPowerVariableAssignment_3(), "rule__PowerState__PowerVariableAssignment_3");
			builder.put(grammarAccess.getObligationStateAccess().getStateNameAssignment_0(), "rule__ObligationState__StateNameAssignment_0");
			builder.put(grammarAccess.getObligationStateAccess().getObligationVariableAssignment_3(), "rule__ObligationState__ObligationVariableAssignment_3");
			builder.put(grammarAccess.getContractStateAccess().getStateNameAssignment_0(), "rule__ContractState__StateNameAssignment_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SymboleoGrammarAccess grammarAccess;

	@Override
	protected InternalSymboleoParser createParser() {
		InternalSymboleoParser result = new InternalSymboleoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SymboleoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SymboleoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
