/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.Obligation;
import ca.uottawa.csmlab.symboleo.symboleo.ObligationState;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Obligation State</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.impl.ObligationStateImpl#getObligationVariable <em>Obligation Variable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObligationStateImpl extends SituationImpl implements ObligationState
{
  /**
   * The cached value of the '{@link #getObligationVariable() <em>Obligation Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObligationVariable()
   * @generated
   * @ordered
   */
  protected Obligation obligationVariable;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObligationStateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.OBLIGATION_STATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Obligation getObligationVariable()
  {
    if (obligationVariable != null && obligationVariable.eIsProxy())
    {
      InternalEObject oldObligationVariable = (InternalEObject)obligationVariable;
      obligationVariable = (Obligation)eResolveProxy(oldObligationVariable);
      if (obligationVariable != oldObligationVariable)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SymboleoPackage.OBLIGATION_STATE__OBLIGATION_VARIABLE, oldObligationVariable, obligationVariable));
      }
    }
    return obligationVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Obligation basicGetObligationVariable()
  {
    return obligationVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObligationVariable(Obligation newObligationVariable)
  {
    Obligation oldObligationVariable = obligationVariable;
    obligationVariable = newObligationVariable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SymboleoPackage.OBLIGATION_STATE__OBLIGATION_VARIABLE, oldObligationVariable, obligationVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SymboleoPackage.OBLIGATION_STATE__OBLIGATION_VARIABLE:
        if (resolve) return getObligationVariable();
        return basicGetObligationVariable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SymboleoPackage.OBLIGATION_STATE__OBLIGATION_VARIABLE:
        setObligationVariable((Obligation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.OBLIGATION_STATE__OBLIGATION_VARIABLE:
        setObligationVariable((Obligation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SymboleoPackage.OBLIGATION_STATE__OBLIGATION_VARIABLE:
        return obligationVariable != null;
    }
    return super.eIsSet(featureID);
  }

} //ObligationStateImpl
