/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionCannotBeAssigned;
import ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Predicate Function Cannot Be Assigned</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PredicateFunctionCannotBeAssignedImpl extends OtherFunctionImpl implements PredicateFunctionCannotBeAssigned
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PredicateFunctionCannotBeAssignedImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SymboleoPackage.Literals.PREDICATE_FUNCTION_CANNOT_BE_ASSIGNED;
  }

} //PredicateFunctionCannotBeAssignedImpl
