/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo.impl;

import ca.uottawa.csmlab.symboleo.symboleo.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SymboleoFactoryImpl extends EFactoryImpl implements SymboleoFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static SymboleoFactory init()
  {
    try
    {
      SymboleoFactory theSymboleoFactory = (SymboleoFactory)EPackage.Registry.INSTANCE.getEFactory(SymboleoPackage.eNS_URI);
      if (theSymboleoFactory != null)
      {
        return theSymboleoFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new SymboleoFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SymboleoFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case SymboleoPackage.MODEL: return createModel();
      case SymboleoPackage.DOMAIN_TYPE: return createDomainType();
      case SymboleoPackage.ALIAS: return createAlias();
      case SymboleoPackage.ENUMERATION: return createEnumeration();
      case SymboleoPackage.ENUM_ITEM: return createEnumItem();
      case SymboleoPackage.REGULAR_TYPE: return createRegularType();
      case SymboleoPackage.ATTRIBUTE: return createAttribute();
      case SymboleoPackage.BASE_TYPE: return createBaseType();
      case SymboleoPackage.ONTOLOGY_TYPE: return createOntologyType();
      case SymboleoPackage.ATTRIBUTE_MODIFIER: return createAttributeModifier();
      case SymboleoPackage.PARAMETER: return createParameter();
      case SymboleoPackage.PARAMETER_TYPE: return createParameterType();
      case SymboleoPackage.VARIABLE: return createVariable();
      case SymboleoPackage.OASSIGNMENT: return createOAssignment();
      case SymboleoPackage.REF: return createRef();
      case SymboleoPackage.ASSIGNMENT: return createAssignment();
      case SymboleoPackage.EXPRESSION: return createExpression();
      case SymboleoPackage.FUNCTION_CALL: return createFunctionCall();
      case SymboleoPackage.OBLIGATION: return createObligation();
      case SymboleoPackage.POWER: return createPower();
      case SymboleoPackage.POWER_FUNCTION: return createPowerFunction();
      case SymboleoPackage.PROPOSITION: return createProposition();
      case SymboleoPackage.PREDICATE_FUNCTION: return createPredicateFunction();
      case SymboleoPackage.OTHER_FUNCTION: return createOtherFunction();
      case SymboleoPackage.EVENT: return createEvent();
      case SymboleoPackage.POINT: return createPoint();
      case SymboleoPackage.POINT_EXPRESSION: return createPointExpression();
      case SymboleoPackage.TIMEVALUE: return createTimevalue();
      case SymboleoPackage.INTERVAL: return createInterval();
      case SymboleoPackage.INTERVAL_EXPRESSION: return createIntervalExpression();
      case SymboleoPackage.SITUATION: return createSituation();
      case SymboleoPackage.POWER_STATE: return createPowerState();
      case SymboleoPackage.OBLIGATION_STATE: return createObligationState();
      case SymboleoPackage.CONTRACT_STATE: return createContractState();
      case SymboleoPackage.OASSIGN_EXPRESSION: return createOAssignExpression();
      case SymboleoPackage.VARIABLE_DOT_EXPRESSION: return createVariableDotExpression();
      case SymboleoPackage.VARIABLE_REF: return createVariableRef();
      case SymboleoPackage.ASSIGN_EXPRESSION: return createAssignExpression();
      case SymboleoPackage.OR: return createOr();
      case SymboleoPackage.AND: return createAnd();
      case SymboleoPackage.EQUALITY: return createEquality();
      case SymboleoPackage.COMPARISON: return createComparison();
      case SymboleoPackage.PLUS: return createPlus();
      case SymboleoPackage.MINUS: return createMinus();
      case SymboleoPackage.MULTI: return createMulti();
      case SymboleoPackage.DIV: return createDiv();
      case SymboleoPackage.PRIMARY_EXPRESSION_RECURSIVE: return createPrimaryExpressionRecursive();
      case SymboleoPackage.PRIMARY_EXPRESSION_FUNCTION_CALL: return createPrimaryExpressionFunctionCall();
      case SymboleoPackage.NEGATED_PRIMARY_EXPRESSION: return createNegatedPrimaryExpression();
      case SymboleoPackage.ATOMIC_EXPRESSION_TRUE: return createAtomicExpressionTrue();
      case SymboleoPackage.ATOMIC_EXPRESSION_FALSE: return createAtomicExpressionFalse();
      case SymboleoPackage.ATOMIC_EXPRESSION_DOUBLE: return createAtomicExpressionDouble();
      case SymboleoPackage.ATOMIC_EXPRESSION_INT: return createAtomicExpressionInt();
      case SymboleoPackage.ATOMIC_EXPRESSION_DATE: return createAtomicExpressionDate();
      case SymboleoPackage.ATOMIC_EXPRESSION_ENUM: return createAtomicExpressionEnum();
      case SymboleoPackage.ATOMIC_EXPRESSION_STRING: return createAtomicExpressionString();
      case SymboleoPackage.ATOMIC_EXPRESSION_PARAMETER: return createAtomicExpressionParameter();
      case SymboleoPackage.TWO_ARG_MATH_FUNCTION: return createTwoArgMathFunction();
      case SymboleoPackage.ONE_ARG_MATH_FUNCTION: return createOneArgMathFunction();
      case SymboleoPackage.THREE_ARG_STRING_FUNCTION: return createThreeArgStringFunction();
      case SymboleoPackage.TWO_ARG_STRING_FUNCTION: return createTwoArgStringFunction();
      case SymboleoPackage.ONE_ARG_STRING_FUNCTION: return createOneArgStringFunction();
      case SymboleoPackage.THREE_ARG_DATE_FUNCTION: return createThreeArgDateFunction();
      case SymboleoPackage.PF_OBLIGATION_SUSPENDED: return createPFObligationSuspended();
      case SymboleoPackage.PF_OBLIGATION_RESUMED: return createPFObligationResumed();
      case SymboleoPackage.PF_OBLIGATION_DISCHARGED: return createPFObligationDischarged();
      case SymboleoPackage.PF_OBLIGATION_TERMINATED: return createPFObligationTerminated();
      case SymboleoPackage.PF_OBLIGATION_TRIGGERED: return createPFObligationTriggered();
      case SymboleoPackage.PF_CONTRACT_SUSPENDED: return createPFContractSuspended();
      case SymboleoPackage.PF_CONTRACT_RESUMED: return createPFContractResumed();
      case SymboleoPackage.PF_CONTRACT_TERMINATED: return createPFContractTerminated();
      case SymboleoPackage.POR: return createPOr();
      case SymboleoPackage.PAND: return createPAnd();
      case SymboleoPackage.PEQUALITY: return createPEquality();
      case SymboleoPackage.PCOMPARISON: return createPComparison();
      case SymboleoPackage.PATOM_RECURSIVE: return createPAtomRecursive();
      case SymboleoPackage.NEGATED_PATOM: return createNegatedPAtom();
      case SymboleoPackage.PATOM_PREDICATE: return createPAtomPredicate();
      case SymboleoPackage.PATOM_FUNCTION: return createPAtomFunction();
      case SymboleoPackage.PATOM_ENUM: return createPAtomEnum();
      case SymboleoPackage.PATOM_VARIABLE: return createPAtomVariable();
      case SymboleoPackage.PATOM_PREDICATE_TRUE_LITERAL: return createPAtomPredicateTrueLiteral();
      case SymboleoPackage.PATOM_PREDICATE_FALSE_LITERAL: return createPAtomPredicateFalseLiteral();
      case SymboleoPackage.PATOM_DOUBLE_LITERAL: return createPAtomDoubleLiteral();
      case SymboleoPackage.PATOM_INT_LITERAL: return createPAtomIntLiteral();
      case SymboleoPackage.PATOM_STRING_LITERAL: return createPAtomStringLiteral();
      case SymboleoPackage.PATOM_DATE_LITERAL: return createPAtomDateLiteral();
      case SymboleoPackage.PREDICATE_FUNCTION_HAPPENS: return createPredicateFunctionHappens();
      case SymboleoPackage.PREDICATE_FUNCTION_WHAPPENS_BEFORE: return createPredicateFunctionWHappensBefore();
      case SymboleoPackage.PREDICATE_FUNCTION_SHAPPENS_BEFORE: return createPredicateFunctionSHappensBefore();
      case SymboleoPackage.PREDICATE_FUNCTION_HAPPENS_WITHIN: return createPredicateFunctionHappensWithin();
      case SymboleoPackage.PREDICATE_FUNCTION_WHAPPENS_BEFORE_EVENT: return createPredicateFunctionWHappensBeforeEvent();
      case SymboleoPackage.PREDICATE_FUNCTION_SHAPPENS_BEFORE_EVENT: return createPredicateFunctionSHappensBeforeEvent();
      case SymboleoPackage.PREDICATE_FUNCTION_HAPPENS_AFTER: return createPredicateFunctionHappensAfter();
      case SymboleoPackage.PREDICATE_FUNCTION_OCCURS: return createPredicateFunctionOccurs();
      case SymboleoPackage.PREDICATE_FUNCTION_ASSIGNMENT: return createPredicateFunctionAssignment();
      case SymboleoPackage.PREDICATE_FUNCTION_ASSIGNMENT_ONLY: return createPredicateFunctionAssignmentOnly();
      case SymboleoPackage.PREDICATE_FUNCTION_IS_EQUAL: return createPredicateFunctionIsEqual();
      case SymboleoPackage.PREDICATE_FUNCTION_IS_OWNER: return createPredicateFunctionIsOwner();
      case SymboleoPackage.PREDICATE_FUNCTION_CANNOT_BE_ASSIGNED: return createPredicateFunctionCannotBeAssigned();
      case SymboleoPackage.VARIABLE_EVENT: return createVariableEvent();
      case SymboleoPackage.POWER_EVENT: return createPowerEvent();
      case SymboleoPackage.OBLIGATION_EVENT: return createObligationEvent();
      case SymboleoPackage.CONTRACT_EVENT: return createContractEvent();
      case SymboleoPackage.POINT_FUNCTION: return createPointFunction();
      case SymboleoPackage.POINT_ATOM_PARAMETER_DOT_EXPRESSION: return createPointAtomParameterDotExpression();
      case SymboleoPackage.POINT_ATOM_OBLIGATION_EVENT: return createPointAtomObligationEvent();
      case SymboleoPackage.POINT_ATOM_CONTRACT_EVENT: return createPointAtomContractEvent();
      case SymboleoPackage.POINT_ATOM_POWER_EVENT: return createPointAtomPowerEvent();
      case SymboleoPackage.TIMEVALUE_INT: return createTimevalueInt();
      case SymboleoPackage.TIMEVALUE_VARIABLE: return createTimevalueVariable();
      case SymboleoPackage.INTERVAL_FUNCTION: return createIntervalFunction();
      case SymboleoPackage.SITUATION_EXPRESSION: return createSituationExpression();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DomainType createDomainType()
  {
    DomainTypeImpl domainType = new DomainTypeImpl();
    return domainType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Alias createAlias()
  {
    AliasImpl alias = new AliasImpl();
    return alias;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Enumeration createEnumeration()
  {
    EnumerationImpl enumeration = new EnumerationImpl();
    return enumeration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EnumItem createEnumItem()
  {
    EnumItemImpl enumItem = new EnumItemImpl();
    return enumItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RegularType createRegularType()
  {
    RegularTypeImpl regularType = new RegularTypeImpl();
    return regularType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BaseType createBaseType()
  {
    BaseTypeImpl baseType = new BaseTypeImpl();
    return baseType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OntologyType createOntologyType()
  {
    OntologyTypeImpl ontologyType = new OntologyTypeImpl();
    return ontologyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttributeModifier createAttributeModifier()
  {
    AttributeModifierImpl attributeModifier = new AttributeModifierImpl();
    return attributeModifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Parameter createParameter()
  {
    ParameterImpl parameter = new ParameterImpl();
    return parameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ParameterType createParameterType()
  {
    ParameterTypeImpl parameterType = new ParameterTypeImpl();
    return parameterType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variable createVariable()
  {
    VariableImpl variable = new VariableImpl();
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OAssignment createOAssignment()
  {
    OAssignmentImpl oAssignment = new OAssignmentImpl();
    return oAssignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ref createRef()
  {
    RefImpl ref = new RefImpl();
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Assignment createAssignment()
  {
    AssignmentImpl assignment = new AssignmentImpl();
    return assignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FunctionCall createFunctionCall()
  {
    FunctionCallImpl functionCall = new FunctionCallImpl();
    return functionCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Obligation createObligation()
  {
    ObligationImpl obligation = new ObligationImpl();
    return obligation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Power createPower()
  {
    PowerImpl power = new PowerImpl();
    return power;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PowerFunction createPowerFunction()
  {
    PowerFunctionImpl powerFunction = new PowerFunctionImpl();
    return powerFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Proposition createProposition()
  {
    PropositionImpl proposition = new PropositionImpl();
    return proposition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunction createPredicateFunction()
  {
    PredicateFunctionImpl predicateFunction = new PredicateFunctionImpl();
    return predicateFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OtherFunction createOtherFunction()
  {
    OtherFunctionImpl otherFunction = new OtherFunctionImpl();
    return otherFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event createEvent()
  {
    EventImpl event = new EventImpl();
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Point createPoint()
  {
    PointImpl point = new PointImpl();
    return point;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PointExpression createPointExpression()
  {
    PointExpressionImpl pointExpression = new PointExpressionImpl();
    return pointExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Timevalue createTimevalue()
  {
    TimevalueImpl timevalue = new TimevalueImpl();
    return timevalue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interval createInterval()
  {
    IntervalImpl interval = new IntervalImpl();
    return interval;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntervalExpression createIntervalExpression()
  {
    IntervalExpressionImpl intervalExpression = new IntervalExpressionImpl();
    return intervalExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Situation createSituation()
  {
    SituationImpl situation = new SituationImpl();
    return situation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PowerState createPowerState()
  {
    PowerStateImpl powerState = new PowerStateImpl();
    return powerState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ObligationState createObligationState()
  {
    ObligationStateImpl obligationState = new ObligationStateImpl();
    return obligationState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ContractState createContractState()
  {
    ContractStateImpl contractState = new ContractStateImpl();
    return contractState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OAssignExpression createOAssignExpression()
  {
    OAssignExpressionImpl oAssignExpression = new OAssignExpressionImpl();
    return oAssignExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDotExpression createVariableDotExpression()
  {
    VariableDotExpressionImpl variableDotExpression = new VariableDotExpressionImpl();
    return variableDotExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableRef createVariableRef()
  {
    VariableRefImpl variableRef = new VariableRefImpl();
    return variableRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AssignExpression createAssignExpression()
  {
    AssignExpressionImpl assignExpression = new AssignExpressionImpl();
    return assignExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Or createOr()
  {
    OrImpl or = new OrImpl();
    return or;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public And createAnd()
  {
    AndImpl and = new AndImpl();
    return and;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Equality createEquality()
  {
    EqualityImpl equality = new EqualityImpl();
    return equality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comparison createComparison()
  {
    ComparisonImpl comparison = new ComparisonImpl();
    return comparison;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Plus createPlus()
  {
    PlusImpl plus = new PlusImpl();
    return plus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Minus createMinus()
  {
    MinusImpl minus = new MinusImpl();
    return minus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Multi createMulti()
  {
    MultiImpl multi = new MultiImpl();
    return multi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Div createDiv()
  {
    DivImpl div = new DivImpl();
    return div;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimaryExpressionRecursive createPrimaryExpressionRecursive()
  {
    PrimaryExpressionRecursiveImpl primaryExpressionRecursive = new PrimaryExpressionRecursiveImpl();
    return primaryExpressionRecursive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimaryExpressionFunctionCall createPrimaryExpressionFunctionCall()
  {
    PrimaryExpressionFunctionCallImpl primaryExpressionFunctionCall = new PrimaryExpressionFunctionCallImpl();
    return primaryExpressionFunctionCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NegatedPrimaryExpression createNegatedPrimaryExpression()
  {
    NegatedPrimaryExpressionImpl negatedPrimaryExpression = new NegatedPrimaryExpressionImpl();
    return negatedPrimaryExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionTrue createAtomicExpressionTrue()
  {
    AtomicExpressionTrueImpl atomicExpressionTrue = new AtomicExpressionTrueImpl();
    return atomicExpressionTrue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionFalse createAtomicExpressionFalse()
  {
    AtomicExpressionFalseImpl atomicExpressionFalse = new AtomicExpressionFalseImpl();
    return atomicExpressionFalse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionDouble createAtomicExpressionDouble()
  {
    AtomicExpressionDoubleImpl atomicExpressionDouble = new AtomicExpressionDoubleImpl();
    return atomicExpressionDouble;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionInt createAtomicExpressionInt()
  {
    AtomicExpressionIntImpl atomicExpressionInt = new AtomicExpressionIntImpl();
    return atomicExpressionInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionDate createAtomicExpressionDate()
  {
    AtomicExpressionDateImpl atomicExpressionDate = new AtomicExpressionDateImpl();
    return atomicExpressionDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionEnum createAtomicExpressionEnum()
  {
    AtomicExpressionEnumImpl atomicExpressionEnum = new AtomicExpressionEnumImpl();
    return atomicExpressionEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionString createAtomicExpressionString()
  {
    AtomicExpressionStringImpl atomicExpressionString = new AtomicExpressionStringImpl();
    return atomicExpressionString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtomicExpressionParameter createAtomicExpressionParameter()
  {
    AtomicExpressionParameterImpl atomicExpressionParameter = new AtomicExpressionParameterImpl();
    return atomicExpressionParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TwoArgMathFunction createTwoArgMathFunction()
  {
    TwoArgMathFunctionImpl twoArgMathFunction = new TwoArgMathFunctionImpl();
    return twoArgMathFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OneArgMathFunction createOneArgMathFunction()
  {
    OneArgMathFunctionImpl oneArgMathFunction = new OneArgMathFunctionImpl();
    return oneArgMathFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ThreeArgStringFunction createThreeArgStringFunction()
  {
    ThreeArgStringFunctionImpl threeArgStringFunction = new ThreeArgStringFunctionImpl();
    return threeArgStringFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TwoArgStringFunction createTwoArgStringFunction()
  {
    TwoArgStringFunctionImpl twoArgStringFunction = new TwoArgStringFunctionImpl();
    return twoArgStringFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OneArgStringFunction createOneArgStringFunction()
  {
    OneArgStringFunctionImpl oneArgStringFunction = new OneArgStringFunctionImpl();
    return oneArgStringFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ThreeArgDateFunction createThreeArgDateFunction()
  {
    ThreeArgDateFunctionImpl threeArgDateFunction = new ThreeArgDateFunctionImpl();
    return threeArgDateFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFObligationSuspended createPFObligationSuspended()
  {
    PFObligationSuspendedImpl pfObligationSuspended = new PFObligationSuspendedImpl();
    return pfObligationSuspended;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFObligationResumed createPFObligationResumed()
  {
    PFObligationResumedImpl pfObligationResumed = new PFObligationResumedImpl();
    return pfObligationResumed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFObligationDischarged createPFObligationDischarged()
  {
    PFObligationDischargedImpl pfObligationDischarged = new PFObligationDischargedImpl();
    return pfObligationDischarged;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFObligationTerminated createPFObligationTerminated()
  {
    PFObligationTerminatedImpl pfObligationTerminated = new PFObligationTerminatedImpl();
    return pfObligationTerminated;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFObligationTriggered createPFObligationTriggered()
  {
    PFObligationTriggeredImpl pfObligationTriggered = new PFObligationTriggeredImpl();
    return pfObligationTriggered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFContractSuspended createPFContractSuspended()
  {
    PFContractSuspendedImpl pfContractSuspended = new PFContractSuspendedImpl();
    return pfContractSuspended;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFContractResumed createPFContractResumed()
  {
    PFContractResumedImpl pfContractResumed = new PFContractResumedImpl();
    return pfContractResumed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PFContractTerminated createPFContractTerminated()
  {
    PFContractTerminatedImpl pfContractTerminated = new PFContractTerminatedImpl();
    return pfContractTerminated;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public POr createPOr()
  {
    POrImpl pOr = new POrImpl();
    return pOr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAnd createPAnd()
  {
    PAndImpl pAnd = new PAndImpl();
    return pAnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PEquality createPEquality()
  {
    PEqualityImpl pEquality = new PEqualityImpl();
    return pEquality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PComparison createPComparison()
  {
    PComparisonImpl pComparison = new PComparisonImpl();
    return pComparison;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomRecursive createPAtomRecursive()
  {
    PAtomRecursiveImpl pAtomRecursive = new PAtomRecursiveImpl();
    return pAtomRecursive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NegatedPAtom createNegatedPAtom()
  {
    NegatedPAtomImpl negatedPAtom = new NegatedPAtomImpl();
    return negatedPAtom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomPredicate createPAtomPredicate()
  {
    PAtomPredicateImpl pAtomPredicate = new PAtomPredicateImpl();
    return pAtomPredicate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomFunction createPAtomFunction()
  {
    PAtomFunctionImpl pAtomFunction = new PAtomFunctionImpl();
    return pAtomFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomEnum createPAtomEnum()
  {
    PAtomEnumImpl pAtomEnum = new PAtomEnumImpl();
    return pAtomEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomVariable createPAtomVariable()
  {
    PAtomVariableImpl pAtomVariable = new PAtomVariableImpl();
    return pAtomVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomPredicateTrueLiteral createPAtomPredicateTrueLiteral()
  {
    PAtomPredicateTrueLiteralImpl pAtomPredicateTrueLiteral = new PAtomPredicateTrueLiteralImpl();
    return pAtomPredicateTrueLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomPredicateFalseLiteral createPAtomPredicateFalseLiteral()
  {
    PAtomPredicateFalseLiteralImpl pAtomPredicateFalseLiteral = new PAtomPredicateFalseLiteralImpl();
    return pAtomPredicateFalseLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomDoubleLiteral createPAtomDoubleLiteral()
  {
    PAtomDoubleLiteralImpl pAtomDoubleLiteral = new PAtomDoubleLiteralImpl();
    return pAtomDoubleLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomIntLiteral createPAtomIntLiteral()
  {
    PAtomIntLiteralImpl pAtomIntLiteral = new PAtomIntLiteralImpl();
    return pAtomIntLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomStringLiteral createPAtomStringLiteral()
  {
    PAtomStringLiteralImpl pAtomStringLiteral = new PAtomStringLiteralImpl();
    return pAtomStringLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PAtomDateLiteral createPAtomDateLiteral()
  {
    PAtomDateLiteralImpl pAtomDateLiteral = new PAtomDateLiteralImpl();
    return pAtomDateLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionHappens createPredicateFunctionHappens()
  {
    PredicateFunctionHappensImpl predicateFunctionHappens = new PredicateFunctionHappensImpl();
    return predicateFunctionHappens;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionWHappensBefore createPredicateFunctionWHappensBefore()
  {
    PredicateFunctionWHappensBeforeImpl predicateFunctionWHappensBefore = new PredicateFunctionWHappensBeforeImpl();
    return predicateFunctionWHappensBefore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionSHappensBefore createPredicateFunctionSHappensBefore()
  {
    PredicateFunctionSHappensBeforeImpl predicateFunctionSHappensBefore = new PredicateFunctionSHappensBeforeImpl();
    return predicateFunctionSHappensBefore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionHappensWithin createPredicateFunctionHappensWithin()
  {
    PredicateFunctionHappensWithinImpl predicateFunctionHappensWithin = new PredicateFunctionHappensWithinImpl();
    return predicateFunctionHappensWithin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionWHappensBeforeEvent createPredicateFunctionWHappensBeforeEvent()
  {
    PredicateFunctionWHappensBeforeEventImpl predicateFunctionWHappensBeforeEvent = new PredicateFunctionWHappensBeforeEventImpl();
    return predicateFunctionWHappensBeforeEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionSHappensBeforeEvent createPredicateFunctionSHappensBeforeEvent()
  {
    PredicateFunctionSHappensBeforeEventImpl predicateFunctionSHappensBeforeEvent = new PredicateFunctionSHappensBeforeEventImpl();
    return predicateFunctionSHappensBeforeEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionHappensAfter createPredicateFunctionHappensAfter()
  {
    PredicateFunctionHappensAfterImpl predicateFunctionHappensAfter = new PredicateFunctionHappensAfterImpl();
    return predicateFunctionHappensAfter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionOccurs createPredicateFunctionOccurs()
  {
    PredicateFunctionOccursImpl predicateFunctionOccurs = new PredicateFunctionOccursImpl();
    return predicateFunctionOccurs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionAssignment createPredicateFunctionAssignment()
  {
    PredicateFunctionAssignmentImpl predicateFunctionAssignment = new PredicateFunctionAssignmentImpl();
    return predicateFunctionAssignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionAssignmentOnly createPredicateFunctionAssignmentOnly()
  {
    PredicateFunctionAssignmentOnlyImpl predicateFunctionAssignmentOnly = new PredicateFunctionAssignmentOnlyImpl();
    return predicateFunctionAssignmentOnly;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionIsEqual createPredicateFunctionIsEqual()
  {
    PredicateFunctionIsEqualImpl predicateFunctionIsEqual = new PredicateFunctionIsEqualImpl();
    return predicateFunctionIsEqual;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionIsOwner createPredicateFunctionIsOwner()
  {
    PredicateFunctionIsOwnerImpl predicateFunctionIsOwner = new PredicateFunctionIsOwnerImpl();
    return predicateFunctionIsOwner;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateFunctionCannotBeAssigned createPredicateFunctionCannotBeAssigned()
  {
    PredicateFunctionCannotBeAssignedImpl predicateFunctionCannotBeAssigned = new PredicateFunctionCannotBeAssignedImpl();
    return predicateFunctionCannotBeAssigned;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableEvent createVariableEvent()
  {
    VariableEventImpl variableEvent = new VariableEventImpl();
    return variableEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PowerEvent createPowerEvent()
  {
    PowerEventImpl powerEvent = new PowerEventImpl();
    return powerEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ObligationEvent createObligationEvent()
  {
    ObligationEventImpl obligationEvent = new ObligationEventImpl();
    return obligationEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ContractEvent createContractEvent()
  {
    ContractEventImpl contractEvent = new ContractEventImpl();
    return contractEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PointFunction createPointFunction()
  {
    PointFunctionImpl pointFunction = new PointFunctionImpl();
    return pointFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PointAtomParameterDotExpression createPointAtomParameterDotExpression()
  {
    PointAtomParameterDotExpressionImpl pointAtomParameterDotExpression = new PointAtomParameterDotExpressionImpl();
    return pointAtomParameterDotExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PointAtomObligationEvent createPointAtomObligationEvent()
  {
    PointAtomObligationEventImpl pointAtomObligationEvent = new PointAtomObligationEventImpl();
    return pointAtomObligationEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PointAtomContractEvent createPointAtomContractEvent()
  {
    PointAtomContractEventImpl pointAtomContractEvent = new PointAtomContractEventImpl();
    return pointAtomContractEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PointAtomPowerEvent createPointAtomPowerEvent()
  {
    PointAtomPowerEventImpl pointAtomPowerEvent = new PointAtomPowerEventImpl();
    return pointAtomPowerEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TimevalueInt createTimevalueInt()
  {
    TimevalueIntImpl timevalueInt = new TimevalueIntImpl();
    return timevalueInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TimevalueVariable createTimevalueVariable()
  {
    TimevalueVariableImpl timevalueVariable = new TimevalueVariableImpl();
    return timevalueVariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntervalFunction createIntervalFunction()
  {
    IntervalFunctionImpl intervalFunction = new IntervalFunctionImpl();
    return intervalFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SituationExpression createSituationExpression()
  {
    SituationExpressionImpl situationExpression = new SituationExpressionImpl();
    return situationExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SymboleoPackage getSymboleoPackage()
  {
    return (SymboleoPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static SymboleoPackage getPackage()
  {
    return SymboleoPackage.eINSTANCE;
  }

} //SymboleoFactoryImpl
