/*
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SymboleoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ca/uottawa/csmlab/symboleo/parser/antlr/internal/InternalSymboleo.tokens");
	}
}
