/*
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo;
import com.google.inject.Injector;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SymboleoStandaloneSetup extends SymboleoStandaloneSetupGenerated {

	public Injector doSetup() {
		return new SymboleoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
