/*
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSymboleoScopeProvider extends DelegatingScopeProvider {
}
