/*
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSymboleoValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage.eINSTANCE);
		return result;
	}
}
