/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract State</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getContractState()
 * @model
 * @generated
 */
public interface ContractState extends Situation
{
} // ContractState
