/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Enumeration#getEnumerationItems <em>Enumeration Items</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getEnumeration()
 * @model
 * @generated
 */
public interface Enumeration extends DomainType
{
  /**
   * Returns the value of the '<em><b>Enumeration Items</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.EnumItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumeration Items</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getEnumeration_EnumerationItems()
   * @model containment="true"
   * @generated
   */
  EList<EnumItem> getEnumerationItems();

} // Enumeration
