/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getDomainName <em>Domain Name</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getDomainTypes <em>Domain Types</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getTimeUnits <em>Time Units</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getContractName <em>Contract Name</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getParameters <em>Parameters</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getVariables <em>Variables</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getPreconditions <em>Preconditions</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getPostconditions <em>Postconditions</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getObligations <em>Obligations</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getSurvivingObligations <em>Surviving Obligations</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getPowers <em>Powers</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Domain Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Name</em>' attribute.
   * @see #setDomainName(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_DomainName()
   * @model
   * @generated
   */
  String getDomainName();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getDomainName <em>Domain Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domain Name</em>' attribute.
   * @see #getDomainName()
   * @generated
   */
  void setDomainName(String value);

  /**
   * Returns the value of the '<em><b>Domain Types</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.DomainType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Types</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_DomainTypes()
   * @model containment="true"
   * @generated
   */
  EList<DomainType> getDomainTypes();

  /**
   * Returns the value of the '<em><b>Time Units</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Units</em>' attribute.
   * @see #setTimeUnits(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_TimeUnits()
   * @model
   * @generated
   */
  String getTimeUnits();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getTimeUnits <em>Time Units</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Units</em>' attribute.
   * @see #getTimeUnits()
   * @generated
   */
  void setTimeUnits(String value);

  /**
   * Returns the value of the '<em><b>Contract Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contract Name</em>' attribute.
   * @see #setContractName(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_ContractName()
   * @model
   * @generated
   */
  String getContractName();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Model#getContractName <em>Contract Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contract Name</em>' attribute.
   * @see #getContractName()
   * @generated
   */
  void setContractName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_Variables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariables();

  /**
   * Returns the value of the '<em><b>Preconditions</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Proposition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preconditions</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_Preconditions()
   * @model containment="true"
   * @generated
   */
  EList<Proposition> getPreconditions();

  /**
   * Returns the value of the '<em><b>Postconditions</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Proposition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postconditions</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_Postconditions()
   * @model containment="true"
   * @generated
   */
  EList<Proposition> getPostconditions();

  /**
   * Returns the value of the '<em><b>Obligations</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Obligation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligations</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_Obligations()
   * @model containment="true"
   * @generated
   */
  EList<Obligation> getObligations();

  /**
   * Returns the value of the '<em><b>Surviving Obligations</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Obligation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surviving Obligations</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_SurvivingObligations()
   * @model containment="true"
   * @generated
   */
  EList<Obligation> getSurvivingObligations();

  /**
   * Returns the value of the '<em><b>Powers</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Power}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Powers</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_Powers()
   * @model containment="true"
   * @generated
   */
  EList<Power> getPowers();

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Proposition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getModel_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<Proposition> getConstraints();

} // Model
