/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obligation State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ObligationState#getObligationVariable <em>Obligation Variable</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getObligationState()
 * @model
 * @generated
 */
public interface ObligationState extends Situation
{
  /**
   * Returns the value of the '<em><b>Obligation Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligation Variable</em>' reference.
   * @see #setObligationVariable(Obligation)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getObligationState_ObligationVariable()
   * @model
   * @generated
   */
  Obligation getObligationVariable();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ObligationState#getObligationVariable <em>Obligation Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obligation Variable</em>' reference.
   * @see #getObligationVariable()
   * @generated
   */
  void setObligationVariable(Obligation value);

} // ObligationState
