/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obligation Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ObligationEvent#getEventName <em>Event Name</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ObligationEvent#getObligationVariable <em>Obligation Variable</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getObligationEvent()
 * @model
 * @generated
 */
public interface ObligationEvent extends Event
{
  /**
   * Returns the value of the '<em><b>Event Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Name</em>' attribute.
   * @see #setEventName(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getObligationEvent_EventName()
   * @model
   * @generated
   */
  String getEventName();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ObligationEvent#getEventName <em>Event Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Name</em>' attribute.
   * @see #getEventName()
   * @generated
   */
  void setEventName(String value);

  /**
   * Returns the value of the '<em><b>Obligation Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligation Variable</em>' reference.
   * @see #setObligationVariable(Obligation)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getObligationEvent_ObligationVariable()
   * @model
   * @generated
   */
  Obligation getObligationVariable();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ObligationEvent#getObligationVariable <em>Obligation Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obligation Variable</em>' reference.
   * @see #getObligationVariable()
   * @generated
   */
  void setObligationVariable(Obligation value);

} // ObligationEvent
