/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>One Arg Math Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getOneArgMathFunction()
 * @model
 * @generated
 */
public interface OneArgMathFunction extends FunctionCall
{
} // OneArgMathFunction
