/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAtom Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PAtomEnum#getEnumeration <em>Enumeration</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PAtomEnum#getEnumItem <em>Enum Item</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPAtomEnum()
 * @model
 * @generated
 */
public interface PAtomEnum extends Proposition
{
  /**
   * Returns the value of the '<em><b>Enumeration</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumeration</em>' reference.
   * @see #setEnumeration(Enumeration)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPAtomEnum_Enumeration()
   * @model
   * @generated
   */
  Enumeration getEnumeration();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PAtomEnum#getEnumeration <em>Enumeration</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumeration</em>' reference.
   * @see #getEnumeration()
   * @generated
   */
  void setEnumeration(Enumeration value);

  /**
   * Returns the value of the '<em><b>Enum Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Item</em>' reference.
   * @see #setEnumItem(EnumItem)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPAtomEnum_EnumItem()
   * @model
   * @generated
   */
  EnumItem getEnumItem();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PAtomEnum#getEnumItem <em>Enum Item</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enum Item</em>' reference.
   * @see #getEnumItem()
   * @generated
   */
  void setEnumItem(EnumItem value);

} // PAtomEnum
