/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAtom Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PAtomPredicate#getPredicateFunction <em>Predicate Function</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPAtomPredicate()
 * @model
 * @generated
 */
public interface PAtomPredicate extends Proposition
{
  /**
   * Returns the value of the '<em><b>Predicate Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate Function</em>' containment reference.
   * @see #setPredicateFunction(PredicateFunction)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPAtomPredicate_PredicateFunction()
   * @model containment="true"
   * @generated
   */
  PredicateFunction getPredicateFunction();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PAtomPredicate#getPredicateFunction <em>Predicate Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate Function</em>' containment reference.
   * @see #getPredicateFunction()
   * @generated
   */
  void setPredicateFunction(PredicateFunction value);

} // PAtomPredicate
