/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PF Contract Suspended</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PFContractSuspended#getNorm <em>Norm</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPFContractSuspended()
 * @model
 * @generated
 */
public interface PFContractSuspended extends PowerFunction
{
  /**
   * Returns the value of the '<em><b>Norm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Norm</em>' attribute.
   * @see #setNorm(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPFContractSuspended_Norm()
   * @model
   * @generated
   */
  String getNorm();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PFContractSuspended#getNorm <em>Norm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Norm</em>' attribute.
   * @see #getNorm()
   * @generated
   */
  void setNorm(String value);

} // PFContractSuspended
