/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PF Obligation Discharged</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PFObligationDischarged#getNorm <em>Norm</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPFObligationDischarged()
 * @model
 * @generated
 */
public interface PFObligationDischarged extends PowerFunction
{
  /**
   * Returns the value of the '<em><b>Norm</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Norm</em>' reference.
   * @see #setNorm(Obligation)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPFObligationDischarged_Norm()
   * @model
   * @generated
   */
  Obligation getNorm();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PFObligationDischarged#getNorm <em>Norm</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Norm</em>' reference.
   * @see #getNorm()
   * @generated
   */
  void setNorm(Obligation value);

} // PFObligationDischarged
