/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointExpression()
 * @model
 * @generated
 */
public interface PointExpression extends EObject
{
} // PointExpression
