/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point Atom Obligation Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomObligationEvent#getObligationEvent <em>Obligation Event</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomObligationEvent()
 * @model
 * @generated
 */
public interface PointAtomObligationEvent extends PointExpression
{
  /**
   * Returns the value of the '<em><b>Obligation Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligation Event</em>' containment reference.
   * @see #setObligationEvent(Event)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomObligationEvent_ObligationEvent()
   * @model containment="true"
   * @generated
   */
  Event getObligationEvent();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomObligationEvent#getObligationEvent <em>Obligation Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obligation Event</em>' containment reference.
   * @see #getObligationEvent()
   * @generated
   */
  void setObligationEvent(Event value);

} // PointAtomObligationEvent
