/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point Atom Power Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomPowerEvent#getPowerEvent <em>Power Event</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomPowerEvent()
 * @model
 * @generated
 */
public interface PointAtomPowerEvent extends PointExpression
{
  /**
   * Returns the value of the '<em><b>Power Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power Event</em>' containment reference.
   * @see #setPowerEvent(Event)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomPowerEvent_PowerEvent()
   * @model containment="true"
   * @generated
   */
  Event getPowerEvent();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomPowerEvent#getPowerEvent <em>Power Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power Event</em>' containment reference.
   * @see #getPowerEvent()
   * @generated
   */
  void setPowerEvent(Event value);

} // PointAtomPowerEvent
