/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.Point#getPointExpression <em>Point Expression</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPoint()
 * @model
 * @generated
 */
public interface Point extends EObject
{
  /**
   * Returns the value of the '<em><b>Point Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point Expression</em>' containment reference.
   * @see #setPointExpression(PointExpression)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPoint_PointExpression()
   * @model containment="true"
   * @generated
   */
  PointExpression getPointExpression();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.Point#getPointExpression <em>Point Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Point Expression</em>' containment reference.
   * @see #getPointExpression()
   * @generated
   */
  void setPointExpression(PointExpression value);

} // Point
