/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point Atom Parameter Dot Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomParameterDotExpression#getVariable <em>Variable</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomParameterDotExpression()
 * @model
 * @generated
 */
public interface PointAtomParameterDotExpression extends PointExpression
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Ref)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomParameterDotExpression_Variable()
   * @model containment="true"
   * @generated
   */
  Ref getVariable();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomParameterDotExpression#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Ref value);

} // PointAtomParameterDotExpression
