/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point Atom Contract Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomContractEvent#getContractEvent <em>Contract Event</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomContractEvent()
 * @model
 * @generated
 */
public interface PointAtomContractEvent extends PointExpression
{
  /**
   * Returns the value of the '<em><b>Contract Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contract Event</em>' containment reference.
   * @see #setContractEvent(Event)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPointAtomContractEvent_ContractEvent()
   * @model containment="true"
   * @generated
   */
  Event getContractEvent();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PointAtomContractEvent#getContractEvent <em>Contract Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contract Event</em>' containment reference.
   * @see #getContractEvent()
   * @generated
   */
  void setContractEvent(Event value);

} // PointAtomContractEvent
