/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Power State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PowerState#getPowerVariable <em>Power Variable</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPowerState()
 * @model
 * @generated
 */
public interface PowerState extends Situation
{
  /**
   * Returns the value of the '<em><b>Power Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power Variable</em>' reference.
   * @see #setPowerVariable(Power)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPowerState_PowerVariable()
   * @model
   * @generated
   */
  Power getPowerVariable();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PowerState#getPowerVariable <em>Power Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power Variable</em>' reference.
   * @see #getPowerVariable()
   * @generated
   */
  void setPowerVariable(Power value);

} // PowerState
