/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Function SHappens Before</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionSHappensBefore#getEvent <em>Event</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionSHappensBefore#getPoint <em>Point</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionSHappensBefore()
 * @model
 * @generated
 */
public interface PredicateFunctionSHappensBefore extends PredicateFunction
{
  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference.
   * @see #setEvent(Event)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionSHappensBefore_Event()
   * @model containment="true"
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionSHappensBefore#getEvent <em>Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' containment reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

  /**
   * Returns the value of the '<em><b>Point</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Point</em>' containment reference.
   * @see #setPoint(Point)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionSHappensBefore_Point()
   * @model containment="true"
   * @generated
   */
  Point getPoint();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionSHappensBefore#getPoint <em>Point</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Point</em>' containment reference.
   * @see #getPoint()
   * @generated
   */
  void setPoint(Point value);

} // PredicateFunctionSHappensBefore
