/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Function Cannot Be Assigned</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionCannotBeAssigned()
 * @model
 * @generated
 */
public interface PredicateFunctionCannotBeAssigned extends OtherFunction
{
} // PredicateFunctionCannotBeAssigned
