/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Function Is Equal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionIsEqual#getArg2 <em>Arg2</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionIsEqual()
 * @model
 * @generated
 */
public interface PredicateFunctionIsEqual extends OtherFunction
{
  /**
   * Returns the value of the '<em><b>Arg2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg2</em>' attribute.
   * @see #setArg2(String)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionIsEqual_Arg2()
   * @model
   * @generated
   */
  String getArg2();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionIsEqual#getArg2 <em>Arg2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg2</em>' attribute.
   * @see #getArg2()
   * @generated
   */
  void setArg2(String value);

} // PredicateFunctionIsEqual
