/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Function Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionAssignment#getEvent <em>Event</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionAssignment#getAssignment <em>Assignment</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionAssignment()
 * @model
 * @generated
 */
public interface PredicateFunctionAssignment extends PredicateFunction
{
  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference.
   * @see #setEvent(Event)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionAssignment_Event()
   * @model containment="true"
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PredicateFunctionAssignment#getEvent <em>Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' containment reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.OAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPredicateFunctionAssignment_Assignment()
   * @model containment="true"
   * @generated
   */
  EList<OAssignment> getAssignment();

} // PredicateFunctionAssignment
