/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expression Recursive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PrimaryExpressionRecursive#getInner <em>Inner</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPrimaryExpressionRecursive()
 * @model
 * @generated
 */
public interface PrimaryExpressionRecursive extends Expression
{
  /**
   * Returns the value of the '<em><b>Inner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inner</em>' containment reference.
   * @see #setInner(Expression)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPrimaryExpressionRecursive_Inner()
   * @model containment="true"
   * @generated
   */
  Expression getInner();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PrimaryExpressionRecursive#getInner <em>Inner</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inner</em>' containment reference.
   * @see #getInner()
   * @generated
   */
  void setInner(Expression value);

} // PrimaryExpressionRecursive
