/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expression Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.PrimaryExpressionFunctionCall#getFunction <em>Function</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPrimaryExpressionFunctionCall()
 * @model
 * @generated
 */
public interface PrimaryExpressionFunctionCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference.
   * @see #setFunction(FunctionCall)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getPrimaryExpressionFunctionCall_Function()
   * @model containment="true"
   * @generated
   */
  FunctionCall getFunction();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.PrimaryExpressionFunctionCall#getFunction <em>Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' containment reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(FunctionCall value);

} // PrimaryExpressionFunctionCall
