/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regular Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.RegularType#getOntologyType <em>Ontology Type</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.RegularType#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.RegularType#getRegularType <em>Regular Type</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRegularType()
 * @model
 * @generated
 */
public interface RegularType extends DomainType
{
  /**
   * Returns the value of the '<em><b>Ontology Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ontology Type</em>' containment reference.
   * @see #setOntologyType(OntologyType)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRegularType_OntologyType()
   * @model containment="true"
   * @generated
   */
  OntologyType getOntologyType();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.RegularType#getOntologyType <em>Ontology Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ontology Type</em>' containment reference.
   * @see #getOntologyType()
   * @generated
   */
  void setOntologyType(OntologyType value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link ca.uottawa.csmlab.symboleo.symboleo.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRegularType_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Regular Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regular Type</em>' reference.
   * @see #setRegularType(RegularType)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getRegularType_RegularType()
   * @model
   * @generated
   */
  RegularType getRegularType();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.RegularType#getRegularType <em>Regular Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Regular Type</em>' reference.
   * @see #getRegularType()
   * @generated
   */
  void setRegularType(RegularType value);

} // RegularType
