/**
 * generated by Xtext 2.31.0
 */
package ca.uottawa.csmlab.symboleo.symboleo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Three Arg String Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ThreeArgStringFunction#getArg2 <em>Arg2</em>}</li>
 *   <li>{@link ca.uottawa.csmlab.symboleo.symboleo.ThreeArgStringFunction#getArg3 <em>Arg3</em>}</li>
 * </ul>
 *
 * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getThreeArgStringFunction()
 * @model
 * @generated
 */
public interface ThreeArgStringFunction extends FunctionCall
{
  /**
   * Returns the value of the '<em><b>Arg2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg2</em>' containment reference.
   * @see #setArg2(Expression)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getThreeArgStringFunction_Arg2()
   * @model containment="true"
   * @generated
   */
  Expression getArg2();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ThreeArgStringFunction#getArg2 <em>Arg2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg2</em>' containment reference.
   * @see #getArg2()
   * @generated
   */
  void setArg2(Expression value);

  /**
   * Returns the value of the '<em><b>Arg3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg3</em>' containment reference.
   * @see #setArg3(Expression)
   * @see ca.uottawa.csmlab.symboleo.symboleo.SymboleoPackage#getThreeArgStringFunction_Arg3()
   * @model containment="true"
   * @generated
   */
  Expression getArg3();

  /**
   * Sets the value of the '{@link ca.uottawa.csmlab.symboleo.symboleo.ThreeArgStringFunction#getArg3 <em>Arg3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg3</em>' containment reference.
   * @see #getArg3()
   * @generated
   */
  void setArg3(Expression value);

} // ThreeArgStringFunction
